"""empty message

Revision ID: 20ec195200cf
Revises: e6c0a5b76520
Create Date: 2024-04-13 15:33:10.029339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20ec195200cf'
down_revision = 'e6c0a5b76520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('item_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=700),
               existing_nullable=True)
        batch_op.alter_column('seller_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=700),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=700),
               existing_nullable=True)
        batch_op.alter_column('seller_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=700),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('seller_photo',
               existing_type=sa.String(length=700),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('item_photo',
               existing_type=sa.String(length=700),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('seller_photo',
               existing_type=sa.String(length=700),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('item_photo',
               existing_type=sa.String(length=700),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
