"""empty message

Revision ID: 2706197c278d
Revises: d83ede0ea667
Create Date: 2024-04-08 19:47:05.450127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2706197c278d'
down_revision = 'd83ede0ea667'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('item_photo', sa.LargeBinary(), nullable=True),
    sa.Column('seller_photo', sa.LargeBinary(), nullable=True),
    sa.Column('total_amount', sa.String(length=100), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cart')
    # ### end Alembic commands ###
