"""empty message

Revision ID: a064c9ba4868
Revises: 40b0226e211b
Create Date: 2024-04-13 13:31:29.515628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a064c9ba4868'
down_revision = '40b0226e211b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('item_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('seller_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('seller_photo',
               existing_type=sa.BLOB(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('seller_photo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('item_photo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('seller_photo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)
        batch_op.alter_column('item_photo',
               existing_type=sa.String(length=255),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
