"""empty message

Revision ID: ad7aa5e471f3
Revises: 2706197c278d
Create Date: 2024-04-09 14:24:12.302373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7aa5e471f3'
down_revision = '2706197c278d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    op.drop_table('users')
    op.drop_table('cart')
    op.drop_table('items')
    op.drop_table('creditcard')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creditcard',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('number', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('seller_name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('description', sa.VARCHAR(length=700), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('item_photo', sa.BLOB(), nullable=True),
    sa.Column('seller_photo', sa.BLOB(), nullable=True),
    sa.Column('price', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cart',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('item_photo', sa.BLOB(), nullable=True),
    sa.Column('seller_photo', sa.BLOB(), nullable=True),
    sa.Column('total_amount', sa.VARCHAR(length=100), nullable=True),
    sa.Column('price', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=True),
    sa.Column('email', sa.VARCHAR(length=100), nullable=True),
    sa.Column('password', sa.VARCHAR(length=100), nullable=True),
    sa.Column('photo', sa.BLOB(), nullable=True),
    sa.Column('number', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('payment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('amount', sa.VARCHAR(length=100), nullable=True),
    sa.Column('number', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
