"""empty message

Revision ID: b760fd38de5e
Revises: a064c9ba4868
Create Date: 2024-04-13 13:44:47.401578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b760fd38de5e'
down_revision = 'a064c9ba4868'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###
