"""empty message

Revision ID: c3f5876361ed
Revises: 11c5c24ee46d
Create Date: 2024-04-08 19:40:33.880457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f5876361ed'
down_revision = '11c5c24ee46d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=700), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('item_photo', sa.LargeBinary(), nullable=True),
    sa.Column('seller_photo', sa.LargeBinary(), nullable=True),
    sa.Column('price', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    # ### end Alembic commands ###
