"""empty message

Revision ID: ffa56d68ac52
Revises: 20ec195200cf
Create Date: 2024-04-13 15:37:18.811937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffa56d68ac52'
down_revision = '20ec195200cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('item_photo',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('seller_photo',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_photo',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.LargeBinary(),
               existing_nullable=True)
        batch_op.alter_column('seller_photo',
               existing_type=sa.VARCHAR(length=700),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('seller_photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)
        batch_op.alter_column('item_photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)

    with op.batch_alter_table('cart', schema=None) as batch_op:
        batch_op.alter_column('seller_photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)
        batch_op.alter_column('item_photo',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=700),
               existing_nullable=True)

    # ### end Alembic commands ###
